# Generated by Django 3.2.15 on 2023-03-05 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_food_produce'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProduceChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='food',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='produce',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.foodchoice'),
        ),
        migrations.AlterField(
            model_name='produce',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.producechoice'),
        ),
    ]
