# Generated by Django 3.2.15 on 2023-03-05 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20230305_0103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='foodchoice',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='produce',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='producechoice',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='producechoice',
            name='category',
            field=models.CharField(choices=[('fruits', 'Fruits'), ('vegetables', 'Vegetables'), ('other', 'Other')], default='other', max_length=255),
        ),
    ]
