# Generated by Django 3.2.15 on 2023-03-05 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20230305_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_clinic_visit',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_food_received',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
