# Generated by Django 3.2.15 on 2023-03-05 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20230305_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='next_clinic_visit',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='next_food_batch',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
