# Generated by Django 3.2.15 on 2023-03-05 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20230304_2157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ['food']},
        ),
        migrations.AlterModelOptions(
            name='produce',
            options={'ordering': ['produce']},
        ),
        migrations.RenameField(
            model_name='food',
            old_name='name',
            new_name='food',
        ),
        migrations.RenameField(
            model_name='produce',
            old_name='name',
            new_name='produce',
        ),
    ]
