# Generated by Django 3.2.15 on 2023-03-05 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20230305_0012'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('maximum_choices', models.IntegerField(default=1, help_text='Maximum number of produce choices allowed in this category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
