# Generated by Django 3.2.15 on 2023-03-05 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20230305_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producecategory',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
