# Generated by Django 3.2.15 on 2023-03-05 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20230305_0051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producecategory',
            name='active',
        ),
        migrations.AddField(
            model_name='producechoice',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
