# Generated by Django 3.2.15 on 2023-03-05 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_order_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_fulfilled',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
