# Generated by Django 3.2.15 on 2023-03-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_order_date_fulfilled'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_scheduled',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
