# Generated by Django 3.2.15 on 2023-03-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_order_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='feed',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='producecategory',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.AddField(
            model_name='producecategory',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('pickup', 'Pickup'), ('delivery', 'Delivery')], default='Pickup', max_length=255),
        ),
    ]
