# Generated by Django 4.1.7 on 2023-05-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0022_user_admin_comments_user_medical_comments_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Whether the user is currently enrolled in the program and is authorized to log in and order food.",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="admin_comments",
            field=models.TextField(
                blank=True, help_text="Comments from DiaCare administrators"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="medical_comments",
            field=models.TextField(
                blank=True,
                help_text="Comments from the doctor, dietician, or clinic regarding the patient's medical conditions",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_comments",
            field=models.TextField(blank=True, help_text="Comments from the patient"),
        ),
    ]
