# Generated by Django 4.1.7 on 2023-05-21 02:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0028_rename_comments_order_patient_comments_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="number",
            field=models.IntegerField(
                default=0,
                help_text="Order number, incremented individually for each user",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="admin_comments",
            field=models.TextField(
                blank=True,
                help_text="Comments from food pharmacy staff regarding this order. Not visible to patient.",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="admin_comments",
            field=models.TextField(
                blank=True,
                help_text="Comments from DiaCare administrators. Not visible to patient.",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="medical_comments",
            field=models.TextField(
                blank=True,
                help_text="Comments from the doctor, dietician, or clinic regarding the patient's medical conditions. Not visible to patient.",
            ),
        ),
    ]
