# Generated by Django 4.1.7 on 2023-05-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0030_alter_producecategory_options_order_cancelled"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="cancelled",
        ),
        migrations.AddField(
            model_name="order",
            name="date_cancelled",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
