# Generated by Django 4.1.7 on 2023-05-21 17:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0031_remove_order_cancelled_order_date_cancelled"),
    ]

    operations = [
        migrations.DeleteModel(
            name="feed",
        ),
        migrations.RemoveField(
            model_name="user",
            name="address",
        ),
    ]
