# Generated by Django 4.1.7 on 2023-05-22 22:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0034_alter_user_dietician_alter_user_doctor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("nonbinary", "Non-binary"),
                ],
                max_length=255,
            ),
        ),
    ]
