# Generated by Django 4.1.7 on 2023-05-23 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0036_alter_user_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScreeningQuestionnaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "c1_q1",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No"), ("unsure", "Unsure")],
                        max_length=255,
                    ),
                ),
                (
                    "c1_q2",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No"), ("unsure", "Unsure")],
                        max_length=255,
                    ),
                ),
                (
                    "c2_q1",
                    models.CharField(
                        choices=[
                            ("often", "Often"),
                            ("sometimes", "Sometimes"),
                            ("never", "Never"),
                            (
                                "dont_know_or_decline_to_answer",
                                "Don't know or decline to answer",
                            ),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "c2_q2",
                    models.CharField(
                        choices=[
                            ("often", "Often"),
                            ("sometimes", "Sometimes"),
                            ("never", "Never"),
                            (
                                "dont_know_or_decline_to_answer",
                                "Don't know or decline to answer",
                            ),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "c2_q3",
                    models.CharField(
                        choices=[
                            ("often", "Often"),
                            ("sometimes", "Sometimes"),
                            ("never", "Never"),
                            (
                                "dont_know_or_decline_to_answer",
                                "Don't know or decline to answer",
                            ),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "c2_q4",
                    models.CharField(
                        choices=[
                            ("often", "Often"),
                            ("sometimes", "Sometimes"),
                            ("never", "Never"),
                            (
                                "dont_know_or_decline_to_answer",
                                "Don't know or decline to answer",
                            ),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "c2_q5",
                    models.CharField(
                        choices=[
                            ("often", "Often"),
                            ("sometimes", "Sometimes"),
                            ("never", "Never"),
                            (
                                "dont_know_or_decline_to_answer",
                                "Don't know or decline to answer",
                            ),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "c3_q1",
                    models.CharField(
                        choices=[
                            ("car", "Car"),
                            ("bus", "Bus"),
                            ("metro", "Metro"),
                            ("ride_share_service", "Ride share service"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "c4_q1",
                    models.CharField(
                        choices=[
                            ("almonds", "Almond"),
                            ("1_cows_milk", "1% Cow's Milk"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "c5_q1",
                    models.CharField(
                        choices=[
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                            ("8_or_more", "8+"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
