# Generated by Django 4.1.7 on 2023-05-23 02:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0037_screeningquestionnaire"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="screeningquestionnaire",
            name="c4_q1",
        ),
        migrations.RemoveField(
            model_name="screeningquestionnaire",
            name="c5_q1",
        ),
        migrations.AddField(
            model_name="screeningquestionnaire",
            name="c3_q2",
            field=models.CharField(
                choices=[("almonds", "Almond"), ("1_cows_milk", "1% Cow's Milk")],
                default=1,
                max_length=255,
                verbose_name="Which type of milk do you prefer?",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="screeningquestionnaire",
            name="c3_q3",
            field=models.CharField(
                choices=[
                    ("1", "1"),
                    ("2", "2"),
                    ("3", "3"),
                    ("4", "4"),
                    ("5", "5"),
                    ("6", "6"),
                    ("7", "7"),
                    ("8_or_more", "8+"),
                ],
                default=1,
                max_length=255,
                verbose_name="How many people live in your house?",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="screeningquestionnaire",
            name="c1_q1",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No"), ("unsure", "Unsure")],
                max_length=255,
                verbose_name="Have you received groceries from us before?",
            ),
        ),
        migrations.AlterField(
            model_name="screeningquestionnaire",
            name="c1_q2",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No"), ("unsure", "Unsure")],
                max_length=255,
                verbose_name="Does your family participate in WIC or SNAP (EBT)?",
            ),
        ),
        migrations.AlterField(
            model_name="screeningquestionnaire",
            name="c2_q1",
            field=models.CharField(
                choices=[
                    ("often", "Often"),
                    ("sometimes", "Sometimes"),
                    ("never", "Never"),
                    (
                        "dont_know_or_decline_to_answer",
                        "Don't know or decline to answer",
                    ),
                ],
                max_length=255,
                verbose_name="We worried our food would run out before we got money to buy more.",
            ),
        ),
        migrations.AlterField(
            model_name="screeningquestionnaire",
            name="c2_q2",
            field=models.CharField(
                choices=[
                    ("often", "Often"),
                    ("sometimes", "Sometimes"),
                    ("never", "Never"),
                    (
                        "dont_know_or_decline_to_answer",
                        "Don't know or decline to answer",
                    ),
                ],
                max_length=255,
                verbose_name="The food we ordered didn't last and we didn't have money to buy more.",
            ),
        ),
        migrations.AlterField(
            model_name="screeningquestionnaire",
            name="c2_q3",
            field=models.CharField(
                choices=[
                    ("often", "Often"),
                    ("sometimes", "Sometimes"),
                    ("never", "Never"),
                    (
                        "dont_know_or_decline_to_answer",
                        "Don't know or decline to answer",
                    ),
                ],
                max_length=255,
                verbose_name="We couldn't afford to eat balanced meals (protein with starch, fruits/vegetables at each meal for the entire family).",
            ),
        ),
        migrations.AlterField(
            model_name="screeningquestionnaire",
            name="c2_q4",
            field=models.CharField(
                choices=[
                    ("often", "Often"),
                    ("sometimes", "Sometimes"),
                    ("never", "Never"),
                    (
                        "dont_know_or_decline_to_answer",
                        "Don't know or decline to answer",
                    ),
                ],
                max_length=255,
                verbose_name="We (you or other adults in your household) have had to cut the size of our meals or skip meals because there wasn't enough money for food.",
            ),
        ),
        migrations.AlterField(
            model_name="screeningquestionnaire",
            name="c2_q5",
            field=models.CharField(
                choices=[
                    ("often", "Often"),
                    ("sometimes", "Sometimes"),
                    ("never", "Never"),
                    (
                        "dont_know_or_decline_to_answer",
                        "Don't know or decline to answer",
                    ),
                ],
                max_length=255,
                verbose_name="We often choose prepackaged food over fresh due to price.",
            ),
        ),
        migrations.AlterField(
            model_name="screeningquestionnaire",
            name="c3_q1",
            field=models.CharField(
                choices=[
                    ("car", "Car"),
                    ("bus", "Bus"),
                    ("metro", "Metro"),
                    ("ride_share_service", "Ride share service"),
                ],
                max_length=255,
                verbose_name="How did you get here today?",
            ),
        ),
    ]
