# Generated by Django 4.1.7 on 2023-05-23 03:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0038_remove_screeningquestionnaire_c4_q1_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_active",
        ),
        migrations.AddField(
            model_name="user",
            name="active",
            field=models.BooleanField(
                default=False,
                help_text="Whether the user is currently enrolled in the Food Pharmacy program and is authorized to log in and order food.",
            ),
        ),
    ]
