# Generated by Django 4.1.7 on 2023-05-23 03:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0039_remove_user_is_active_user_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="screeningquestionnaire",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="screening_questionnaire",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
