# Generated by Django 4.1.7 on 2023-05-23 03:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0040_alter_screeningquestionnaire_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
