# Generated by Django 4.1.7 on 2023-05-23 03:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0041_user_user_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
