# Generated by Django 4.1.7 on 2023-05-23 04:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0042_alter_user_user_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="screeningquestionnaire",
            name="date_completed",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
