# Generated by Django 4.1.7 on 2023-05-24 00:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0044_alter_screeningquestionnaire_options_user_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.CharField(max_length=512),
        ),
    ]
