# Generated by Django 4.1.7 on 2023-05-24 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0048_securelink_delete_emailverificationlink"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailVerificationLink",
            fields=[
                (
                    "securelink_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="app.securelink",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
            ],
            bases=("app.securelink",),
        ),
    ]
