# Generated by Django 4.1.7 on 2023-05-24 05:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0050_accountapprovallink_passwordresetlink"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="securelink",
            options={"ordering": ["-time_created"]},
        ),
    ]
