# Generated by Django 4.1.7 on 2023-07-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0053_remove_user_last_clinic_visit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="admin_comments",
            field=models.TextField(
                blank=True,
                help_text="Comments from Food Pharmacy App administrators. Not visible to patient.",
            ),
        ),
    ]
