# Generated by Django 4.1.7 on 2023-07-03 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0054_alter_user_admin_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="dietician",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.dietician",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.doctor",
            ),
        ),
    ]
