# Generated by Django 4.1.7 on 2023-07-06 03:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0055_alter_user_dietician_alter_user_doctor"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PasswordResetLink",
        ),
    ]
